--=======================================================--
-- Magnitude -
--=======================================================--

-- find total customers by countries --
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY COUNT(customer_key) DESC

-- find the total customers by gender --
SELECT
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY COUNT(customer_key) DESC

-- find the total products by category --
SELECT
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_customers DESC

-- what is the average costs in each category ? 
SELECT
	category,
	AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC

-- What is the total revenue generated for each category ?
SELECT
	SUM(f.sales_amount) AS total_revenue,
	pr.category
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS pr
ON pr.product_key = f.product_key
GROUP BY pr.category
ORDER BY total_revenue DESC

-- what is the total revenue generated by each customer 
SELECT 
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON f.customer_key = c.customer_key
GROUP BY c.customer_key,
	c.first_name,
	c.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?
SELECT 
	c.country,
	SUM(f.quantity) AS distribiution
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY distribiution DESC
